name: amity_sdk
description: The SDK that enables social features such as Feeds, Groups,
  Profiles, Content Posts, and Social Media Type Interactions
version: 0.30.0
homepage: https://amity.co
documentation: https://docs.amity.co/social/flutter-beta

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  byte_util: ^3.0.0
  collection: ^1.17.0
  dio: ^5.2.1+1
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  # http: ^1.1.0
  mqtt_client: ^9.7.4
  path_provider: ^2.0.15
  socket_io_client: ^1.0.2
  uuid: ^4.2.1
  amity_sdk_api: ^0.0.1
# Add the lib from the pub dev before deploying
  # amity_api:
  #   path: ../amity_api

dev_dependencies:
  build_runner: ^2.1.11
  flutter_dotenv: ^5.0.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: ^1.21.1

assets:
  - .env
  - dotenv
